<a href="https://colab.research.google.com/github/noushadkhan01/upload_project_to_PyPi/blob/master/upload_my_methods_to_pypi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[see medium article refrence](https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56)
and 
[pypi org refrence](https://packaging.python.org/tutorials/packaging-projects/)

In [1]:
!git clone https://github.com/noushadkhan01/my_methods

Cloning into 'my_methods'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 531 (delta 12), reused 0 (delta 0), pack-reused 509
Receiving objects: 100% (531/531), 133.38 KiB | 12.13 MiB/s, done.
Resolving deltas: 100% (316/316), done.


In [2]:
%cd my_methods

/content/my_methods


In [3]:
!python setup.py sdist

running sdist
running egg_info
creating my_methods.egg-info
writing my_methods.egg-info/PKG-INFO
writing dependency_links to my_methods.egg-info/dependency_links.txt
writing top-level names to my_methods.egg-info/top_level.txt
writing manifest file 'my_methods.egg-info/SOURCES.txt'
writing manifest file 'my_methods.egg-info/SOURCES.txt'
running check
creating my_methods-0.0.4
creating my_methods-0.0.4/my_methods
creating my_methods-0.0.4/my_methods.egg-info
copying files to my_methods-0.0.4...
copying LICENSE.txt -> my_methods-0.0.4
copying README.md -> my_methods-0.0.4
copying setup.cfg -> my_methods-0.0.4
copying setup.py -> my_methods-0.0.4
copying my_methods/__init__.py -> my_methods-0.0.4/my_methods
copying my_methods/choose_best_classifier.py -> my_methods-0.0.4/my_methods
copying my_methods/choose_best_regressor.py -> my_methods-0.0.4/my_methods
copying my_methods/choose_optimal_number_of_clusters.py -> my_methods-0.0.4/my_methods
copying my_methods/get_cross_validation.py -> my

In [4]:
!python3 -m pip install --user --upgrade twine

     |████████████████████████████████| 61kB 7.1MB/s 
     |████████████████████████████████| 921kB 16.8MB/s 
     |████████████████████████████████| 2.7MB 33.3MB/s 
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [5]:
!!python -m twine upload dist/*

['Uploading distributions to https://upload.pypi.org/legacy/',
 'Enter your username: noushadkhan01',
 '/root/.local/lib/python3.6/site-packages/twine/auth.py:68: UserWarning: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.',
 '  warnings.warn(str(exc))',
 'Enter your password: ',
 'Uploading my_methods-0.0.4.tar.gz',
 '',
 '  0% 0.00/14.5k [00:00<?, ?B/s]',
 ' 55% 8.00k/14.5k [00:00<00:00, 36.5kB/s]',
 '100% 14.5k/14.5k [00:01<00:00, 11.8kB/s]',
 '',
 'View at:',
 'https://pypi.org/project/my-methods/0.0.4/']

In [6]:
!pip install my_methods

  Created wheel for my-methods: filename=my_methods-0.0.4-cp36-none-any.whl size=17029 sha256=834b3d42627eaa616c5ce0ea52bb822f3551caf5f6e07ed5e8340e0c3ec473ea
  Stored in directory: /root/.cache/pip/wheels/ff/a7/53/3b3976f318a0a46e8273d805fa99a3827f057bfa314187b596
Successfully built my-methods


In [0]:
import my_methods

In [0]:
from my_methods import choose_best_classifier

In [0]:
from my_methods import matrix_multiplication_without_numpy as mm

In [0]:
from my_methods.transpose_of_matrix_without_numpy import transpose_without_numpy

In [11]:
transpose_without_numpy([[1, 2], [5, 6]])

[[1, 5], [2, 6]]

In [12]:
import numpy as np
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.array(transpose_without_numpy(matrix))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [15]:
matrix = np.array([[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
matrix

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
np.array(transpose_without_numpy(matrix))

array([[ 5, 10],
       [ 6, 11],
       [ 7, 12],
       [ 8, 13],
       [ 9, 14]])